### PR TITLE
Add Postgres support

### PR DESCRIPTION
**Pull request by petergoldstein**

### CODE REVIEW

**Comment by wbotelhos** [comment]
@petergoldstein could you rebase and try again, please?

**Comment by petergoldstein** [comment]
@petergoldstein So the way you reorganized requires much more than a rebase.  Some of it doesn't quite make sense for a multi-db setup (for example, you don't want a dedicated `mysql.rb` file).  I can pull it together, but it's a larger change than just a rebase.

**Comment by petergoldstein** [comment]
Closing this in favor of #12 , which is rebased and restructured for code changes.

**Comment by wbotelhos** [comment]
It was [already there](https://github.com/wbotelhos/rating/blob/c615c3808865642a78eb5d0acba8e9f7aaeff0d3/spec/rails_helper.rb#L9), I've just refactored to expose the hard dependency.

I recommend the following:

1. Save your diff;
2. Reset hard to the root good;
3. Re-apply the diff manually;
4. Force the branch.

**Pull request closed without merging**
